version: "3.8"

services:
  web:
    restart: unless-stopped
    build: .
    container_name: admire-events
    depends_on:
      - database
    volumes:
      - images-avatar-small:/var/www/html/images_avatar_small
      - images:/var/www/html/images
      - avatars:/var/www/html/avatars
    stdin_open: true
    tty: true
    networks:
      - app_network
      - server

  database:
    restart: unless-stopped
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: admire_events
      MYSQL_DATABASE: seapl_database
      MYSQL_USER: seapl_database
      MYSQL_PASSWORD: database_seapl
    networks:
      - app_network

volumes:
  images-avatar-small:
  images:
  avatars:

networks:
  app_network:
    driver: bridge
  server:
    external: true
